field: 4af3b294-4ebe-4043-9f2c-63468570f33f
fieldLayouts:
  4c89eb0e-60cd-4496-854f-d16ace68e11c:
    tabs:
      -
        elements:
          -
            fieldUid: c5e020af-3c15-42d6-9164-74a0ee1da86d
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 0d41cca9-d36e-440b-a337-0cb4d898ad8c
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: 5b7d23fb-a87a-462f-b724-9cec32497c01
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            fieldUid: d071180c-4041-4b62-82a0-ecf144b9de36
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 5b888a96-8ec8-49a7-9677-19a59d02729a
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 1dd47429-a33c-4dcb-aacf-59321f2f4ecc
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: e8350ee0-288e-4b0b-a576-0f98347f3af9
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 05805147-8b4f-42c3-a087-fb99308fe870
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  05805147-8b4f-42c3-a087-fb99308fe870:
    contentColumnType: string
    fieldGroup: null
    handle: hilfsvideo_q
    instructions: ''
    name: Hilfsvideo
    searchable: false
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds:
        - video
      defaultUploadLocationSource: 'volume:5f0e5dbb-8cba-49d5-8a1c-e7b7bf94b7a5'
      defaultUploadLocationSubpath: help_videos
      limit: '1'
      localizeRelations: false
      previewMode: full
      restrictFiles: '1'
      selectionLabel: ''
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: true
      singleUploadLocationSource: 'volume:5f0e5dbb-8cba-49d5-8a1c-e7b7bf94b7a5'
      singleUploadLocationSubpath: ''
      source: null
      sources: '*'
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  0d41cca9-d36e-440b-a337-0cb4d898ad8c:
    contentColumnType: string
    fieldGroup: null
    handle: art
    instructions: ''
    name: Art
    searchable: true
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - Aufgabe
            -
              - value
              - aufgabe
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - Umfrage
            -
              - value
              - umfrage
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  1dd47429-a33c-4dcb-aacf-59321f2f4ecc:
    contentColumnType: text
    fieldGroup: null
    handle: h5p
    instructions: "hier bitte den vollständigen embed Code angeben. Beispiel:\r\n<iframe src=\"https://h5p.test-dilewe.de/wp-admin/admin-ajax.php?action=h5p_embed&id=19\" width=\"958\" height=\"918\" frameborder=\"0\" allowfullscreen=\"allowfullscreen\"></iframe><script src=\"https://h5p.test-dilewe.de/wp-content/plugins/h5p/h5p-php-library/js/h5p-resizer.js\" charset=\"UTF-8\"></script>"
    name: 'h5p Element'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  5b7d23fb-a87a-462f-b724-9cec32497c01:
    contentColumnType: string
    fieldGroup: null
    handle: benutzereingabe
    instructions: ''
    name: Benutzereingabe
    searchable: true
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - Texteingabe
            -
              - value
              - texteingabe
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - Dateiupload
            -
              - value
              - dateiupload
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'keine Eingabe'
            -
              - value
              - ka
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  5b888a96-8ec8-49a7-9677-19a59d02729a:
    contentColumnType: string
    fieldGroup: null
    handle: aufgabeInhalt
    instructions: ''
    name: __blank__
    searchable: false
    settings:
      columns:
        __assoc__:
          -
            - 3a4e723a-d96b-4b9d-8228-3cffb91dba7e
            -
              __assoc__:
                -
                  - width
                  - ''
      contentTable: '{{%stc_7_aufgabeinhalt}}'
      fieldLayout: matrix
      maxRows: ''
      minRows: ''
      placeholderKey: null
      propagationMethod: all
      selectionLabel: 'Baustein hinzufügen'
      staticField: '1'
    translationKeyFormat: null
    translationMethod: site
    type: verbb\supertable\fields\SuperTableField
  c5e020af-3c15-42d6-9164-74a0ee1da86d:
    contentColumnType: text
    fieldGroup: null
    handle: titelDerAufgabe
    instructions: ''
    name: 'Titel der Aufgabe'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  d071180c-4041-4b62-82a0-ecf144b9de36:
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: ''
    name: Text
    searchable: true
    settings:
      availableTransforms: ''
      availableVolumes: ''
      cleanupHtml: true
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: erweitert.json
      removeEmptyTags: '1'
      removeInlineStyles: ''
      removeNbsp: ''
      showHtmlButtonForNonAdmins: '1'
      showUnpermittedFiles: true
      showUnpermittedVolumes: true
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  e8350ee0-288e-4b0b-a576-0f98347f3af9:
    contentColumnType: boolean
    fieldGroup: null
    handle: nummerierung
    instructions: ''
    name: Nummerierung
    searchable: false
    settings:
      default: true
      offLabel: Inaktiv
      onLabel: Aktiv
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
handle: aufgabe
name: 'Aufgabe / Umfrage'
sortOrder: 12
