field: 35aaa38f-a3ed-435f-8616-1d9cbc7fc65c
fieldLayouts:
  94d30804-6445-45d5-a431-f71895619761:
    tabs:
      -
        elements:
          -
            fieldUid: 8075246b-4d57-4926-90af-7839fa8f569e
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 2d3ab860-94fd-4694-88e3-385318ea76e2
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            fieldUid: 673ff94a-6f5a-4fe2-8024-79ef34806d8a
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            fieldUid: 2491ac6c-8f29-4d2e-a56b-5597a63f82f5
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 04719e38-9772-4c1e-8bbc-2552ec47c8b0
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  04719e38-9772-4c1e-8bbc-2552ec47c8b0:
    contentColumnType: string
    fieldGroup: null
    handle: quersliderAufgabenInhalt
    instructions: ''
    name: __blank__
    searchable: false
    settings:
      columns:
        __assoc__:
          -
            - ab6348a4-5bdf-49af-91a3-b0782152a42c
            -
              __assoc__:
                -
                  - width
                  - ''
      contentTable: '{{%stc_51_querslideraufgabeninhalt}}'
      fieldLayout: matrix
      maxRows: '1'
      minRows: '1'
      placeholderKey: null
      propagationMethod: all
      selectionLabel: ''
      staticField: '1'
    translationKeyFormat: null
    translationMethod: site
    type: verbb\supertable\fields\SuperTableField
  2491ac6c-8f29-4d2e-a56b-5597a63f82f5:
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: ''
    name: Text
    searchable: false
    settings:
      availableTransforms: ''
      availableVolumes: ''
      cleanupHtml: true
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: erweitert.json
      removeEmptyTags: '1'
      removeInlineStyles: ''
      removeNbsp: ''
      showHtmlButtonForNonAdmins: '1'
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  2d3ab860-94fd-4694-88e3-385318ea76e2:
    contentColumnType: string
    fieldGroup: null
    handle: art
    instructions: ''
    name: Art
    searchable: false
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - Aufgabe
            -
              - value
              - aufgabe
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Umfrage
            -
              - value
              - umfrage
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  673ff94a-6f5a-4fe2-8024-79ef34806d8a:
    contentColumnType: string
    fieldGroup: null
    handle: benutzereingabe
    instructions: ''
    name: Benutzereingabe
    searchable: false
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - Texteingabe
            -
              - value
              - texteingabe
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - Dateiupload
            -
              - value
              - dateiupload
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'keine Eingabe'
            -
              - value
              - ka
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  8075246b-4d57-4926-90af-7839fa8f569e:
    contentColumnType: text
    fieldGroup: null
    handle: titelDerAufgabe
    instructions: ''
    name: 'Titel der Aufgabe'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: aufgabe
name: Aufgabe
sortOrder: 6
