field: 4af3b294-4ebe-4043-9f2c-63468570f33f
fieldLayouts:
  1b2f0612-520d-4813-bef2-90e7e81df0d6:
    tabs:
      -
        elements:
          -
            fieldUid: a6df6368-e886-4eb9-b366-40d8f07c5c39
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 184162db-6603-4c8b-84c0-3b3996b64445
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 6c4c944c-a1c1-4c7a-8da6-9c6fe550c662
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  184162db-6603-4c8b-84c0-3b3996b64445:
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: ''
    name: Text
    searchable: true
    settings:
      availableTransforms: ''
      availableVolumes: '*'
      cleanupHtml: true
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: erweitert.json
      removeEmptyTags: '1'
      removeInlineStyles: ''
      removeNbsp: ''
      showHtmlButtonForNonAdmins: ''
      showUnpermittedFiles: false
      showUnpermittedVolumes: true
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  6c4c944c-a1c1-4c7a-8da6-9c6fe550c662:
    contentColumnType: boolean
    fieldGroup: null
    handle: nummerierung
    instructions: ''
    name: Nummerierung
    searchable: false
    settings:
      default: true
      offLabel: Inaktiv
      onLabel: Aktiv
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
  a6df6368-e886-4eb9-b366-40d8f07c5c39:
    contentColumnType: string
    fieldGroup: null
    handle: bild
    instructions: ''
    name: Bild
    searchable: true
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds:
        - image
      defaultUploadLocationSource: 'volume:5f0e5dbb-8cba-49d5-8a1c-e7b7bf94b7a5'
      defaultUploadLocationSubpath: ''
      limit: '1'
      localizeRelations: false
      previewMode: full
      restrictFiles: '1'
      selectionLabel: ''
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:5f0e5dbb-8cba-49d5-8a1c-e7b7bf94b7a5'
      singleUploadLocationSubpath: bilder
      source: null
      sources: '*'
      targetSiteId: null
      useSingleFolder: true
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
handle: bildtabelle
name: Bildtabelle
sortOrder: 14
