field: a6ca8dd3-3275-44ec-9e6c-68cf3996ce56
fieldLayouts:
  10f97b1c-78cd-4089-8b41-66c2848e5a59:
    tabs:
      -
        elements:
          -
            fieldUid: f1ae223c-0399-4f74-b9e5-896ac9668412
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 8ed7121b-c885-4d8e-b189-7bade36a023c
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 83000fab-f48b-42db-873b-5751b7097f63
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  83000fab-f48b-42db-873b-5751b7097f63:
    contentColumnType: string(255)
    fieldGroup: null
    handle: urldownload
    instructions: 'Alternativ kann auch eine URL für den Dateidownload angegeben werden, dabei das Dateifeld ignoriert'
    name: 'Url des downloads (alternativ)'
    searchable: false
    settings:
      maxLength: '255'
      placeholder: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Url
  8ed7121b-c885-4d8e-b189-7bade36a023c:
    contentColumnType: string
    fieldGroup: null
    handle: datei
    instructions: ''
    name: Datei
    searchable: false
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds:
        - audio
        - image
        - excel
        - html
        - json
        - javascript
        - compressed
        - pdf
        - powerpoint
        - video
        - word
      defaultUploadLocationSource: 'volume:5f0e5dbb-8cba-49d5-8a1c-e7b7bf94b7a5'
      defaultUploadLocationSubpath: ''
      limit: '1'
      localizeRelations: false
      previewMode: full
      restrictFiles: '1'
      selectionLabel: ''
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: true
      singleUploadLocationSource: 'volume:5f0e5dbb-8cba-49d5-8a1c-e7b7bf94b7a5'
      singleUploadLocationSubpath: downloads/
      source: null
      sources: '*'
      targetSiteId: null
      useSingleFolder: true
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  f1ae223c-0399-4f74-b9e5-896ac9668412:
    contentColumnType: text
    fieldGroup: null
    handle: beschreibung
    instructions: ''
    name: Beschreibung
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: download
name: Download
sortOrder: 7
