field: a6ca8dd3-3275-44ec-9e6c-68cf3996ce56
fieldLayouts:
  63341894-70bf-4f6e-b50e-01479f404eb8:
    tabs:
      -
        elements:
          -
            fieldUid: e46bd1a9-46df-409e-b86a-5870f0505542
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 3449c5d4-f89b-4a9d-a949-4403804326f5
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            fieldUid: ec217417-b0e9-46d8-b85a-fce91a639ab5
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            fieldUid: 539364b5-d156-4a88-a3bb-9c433d2e1ab1
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            fieldUid: c2e1207a-d8e2-4b55-b1fc-6e5fda448f94
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  3449c5d4-f89b-4a9d-a949-4403804326f5:
    contentColumnType: datetime
    fieldGroup: null
    handle: start
    instructions: ''
    name: start
    searchable: false
    settings:
      max: null
      min: null
      minuteIncrement: '30'
      showDate: false
      showTime: true
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Date
  539364b5-d156-4a88-a3bb-9c433d2e1ab1:
    contentColumnType: string
    fieldGroup: null
    handle: untertitel
    instructions: ''
    name: __blank__
    searchable: false
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - 'kein Untertitel'
            -
              - value
              - none
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - deutsch
            -
              - value
              - de
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - englisch
            -
              - value
              - en
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - französisch
            -
              - value
              - fr
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - spanisch
            -
              - value
              - sp
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  c2e1207a-d8e2-4b55-b1fc-6e5fda448f94:
    contentColumnType: text
    fieldGroup: null
    handle: embedUnterschrift
    instructions: ''
    name: 'Video Unterschrift'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  e46bd1a9-46df-409e-b86a-5870f0505542:
    contentColumnType: text
    fieldGroup: null
    handle: urlDesStreams
    instructions: 'Hier kann eine Vimeo oder YouTube URL eingegeben werden. NICHT der embedding code.'
    name: 'url des Videos'
    searchable: false
    settings:
      url: ''
    translationKeyFormat: null
    translationMethod: none
    type: wrav\oembed\fields\OembedField
  ec217417-b0e9-46d8-b85a-fce91a639ab5:
    contentColumnType: datetime
    fieldGroup: null
    handle: ende
    instructions: ''
    name: ende
    searchable: false
    settings:
      max: null
      min: null
      minuteIncrement: '30'
      showDate: false
      showTime: true
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Date
handle: embeddedVideoAudio
name: 'Video/Audio einbinden (z.B. Youtube, Vimeo etc.)'
sortOrder: 5
