field: a6ca8dd3-3275-44ec-9e6c-68cf3996ce56
fieldLayouts:
  ee865523-336f-4bdc-9e48-735fb99eb12b:
    tabs:
      -
        elements:
          -
            fieldUid: d08e7439-522c-4bc3-8ee3-2fbb5f934b02
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 3b170972-0185-46ef-b919-a95469db3c37
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 143fa9b5-76f8-4b91-bc44-121ee37da20f
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  143fa9b5-76f8-4b91-bc44-121ee37da20f:
    contentColumnType: mediumtext
    fieldGroup: null
    handle: galerietext
    instructions: ''
    name: Galerietext
    searchable: false
    settings:
      availableTransforms: ''
      availableVolumes: '*'
      cleanupHtml: true
      columnType: mediumtext
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: erweitert.json
      removeEmptyTags: '1'
      removeInlineStyles: ''
      removeNbsp: '1'
      showHtmlButtonForNonAdmins: '1'
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  3b170972-0185-46ef-b919-a95469db3c37:
    contentColumnType: text
    fieldGroup: null
    handle: bildunterschriften
    instructions: 'Hier kann f端r jedes Bild eine neue Zeile f端r die Unterschriften hinzugef端gt werden'
    name: Bildunterschriften
    searchable: false
    settings:
      addRowLabel: 'Bildunterschrift hinzuf端gen'
      columnType: text
      columns:
        __assoc__:
          -
            - col1
            -
              __assoc__:
                -
                  - heading
                  - ''
                -
                  - handle
                  - bildunterschrift
                -
                  - width
                  - ''
                -
                  - type
                  - singleline
      defaults:
        -
          __assoc__:
            -
              - col1
              - ''
      maxRows: ''
      minRows: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Table
  d08e7439-522c-4bc3-8ee3-2fbb5f934b02:
    contentColumnType: string
    fieldGroup: null
    handle: bilder
    instructions: ''
    name: Bilder
    searchable: false
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds:
        - image
      defaultUploadLocationSource: 'volume:5f0e5dbb-8cba-49d5-8a1c-e7b7bf94b7a5'
      defaultUploadLocationSubpath: ''
      limit: ''
      localizeRelations: false
      previewMode: full
      restrictFiles: '1'
      selectionLabel: ''
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: true
      singleUploadLocationSource: 'volume:5f0e5dbb-8cba-49d5-8a1c-e7b7bf94b7a5'
      singleUploadLocationSubpath: bilder/
      source: null
      sources: '*'
      targetSiteId: null
      useSingleFolder: true
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
handle: galerie
name: Galerie
sortOrder: 8
