field: 35aaa38f-a3ed-435f-8616-1d9cbc7fc65c
fieldLayouts:
  23a5b9f6-b5aa-4eac-8892-ccf2a28d91c8:
    tabs:
      -
        elements:
          -
            fieldUid: edd315f8-55fa-421b-ac04-8eef3aebbf3f
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 829c0e28-3402-4c22-befe-2ba714d4dc23
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 6da2bb52-a19d-46be-9c6d-b14773d3991c
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  6da2bb52-a19d-46be-9c6d-b14773d3991c:
    contentColumnType: text
    fieldGroup: null
    handle: galerietext
    instructions: ''
    name: Einleitungstext
    searchable: false
    settings:
      availableTransforms: ''
      availableVolumes: ''
      cleanupHtml: true
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: erweitert.json
      removeEmptyTags: '1'
      removeInlineStyles: ''
      removeNbsp: ''
      showHtmlButtonForNonAdmins: '1'
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  829c0e28-3402-4c22-befe-2ba714d4dc23:
    contentColumnType: text
    fieldGroup: null
    handle: bildunterschriften
    instructions: ''
    name: Bildunterschriften
    searchable: false
    settings:
      addRowLabel: 'Bildunterschrift hinzufügen'
      columnType: text
      columns:
        __assoc__:
          -
            - col1
            -
              __assoc__:
                -
                  - heading
                  - ''
                -
                  - handle
                  - bildunterschrift
                -
                  - width
                  - ''
                -
                  - type
                  - singleline
      defaults:
        -
          __assoc__:
            -
              - col1
              - ''
      maxRows: ''
      minRows: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Table
  edd315f8-55fa-421b-ac04-8eef3aebbf3f:
    contentColumnType: string
    fieldGroup: null
    handle: bilder
    instructions: ''
    name: Bilder
    searchable: false
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds:
        - image
      defaultUploadLocationSource: 'volume:5f0e5dbb-8cba-49d5-8a1c-e7b7bf94b7a5'
      defaultUploadLocationSubpath: ''
      limit: ''
      localizeRelations: false
      previewMode: full
      restrictFiles: '1'
      selectionLabel: ''
      showSiteMenu: true
      showUnpermittedFiles: true
      showUnpermittedVolumes: true
      singleUploadLocationSource: 'volume:5f0e5dbb-8cba-49d5-8a1c-e7b7bf94b7a5'
      singleUploadLocationSubpath: bilder
      source: null
      sources: '*'
      targetSiteId: null
      useSingleFolder: true
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
handle: galerie
name: Galerie
sortOrder: 8
