field: ab6348a4-5bdf-49af-91a3-b0782152a42c
fieldLayouts:
  9be542e2-fd82-406e-8966-8d998cc2954c:
    tabs:
      -
        elements:
          -
            fieldUid: c81b867e-77f8-4846-9525-6b164bff0d08
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: a295f37f-e124-44a3-bd35-b0efa1de3ab0
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: c21507c1-a27d-40a4-ad6d-34119fb8bf6e
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  a295f37f-e124-44a3-bd35-b0efa1de3ab0:
    contentColumnType: text
    fieldGroup: null
    handle: unterschrift_embed
    instructions: ''
    name: __blank__
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  c21507c1-a27d-40a4-ad6d-34119fb8bf6e:
    contentColumnType: text
    fieldGroup: null
    handle: urheber_embed
    instructions: ''
    name: Urheber
    searchable: false
    settings:
      availableTransforms: ''
      availableVolumes: ''
      cleanupHtml: true
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: Simple.json
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: ''
      showHtmlButtonForNonAdmins: ''
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  c81b867e-77f8-4846-9525-6b164bff0d08:
    contentColumnType: text
    fieldGroup: null
    handle: h5p_embed
    instructions: "hier bitte den vollständigen embed Code angeben. Beispiel:\r\n<iframe src=\"https://h5p.test-dilewe.de/wp-admin/admin-ajax.php?action=h5p_embed&id=19\" width=\"958\" height=\"918\" frameborder=\"0\" allowfullscreen=\"allowfullscreen\"></iframe><script src=\"https://h5p.test-dilewe.de/wp-content/plugins/h5p/h5p-php-library/js/h5p-resizer.js\" charset=\"UTF-8\"></script>"
    name: 'Freier Embed (H5P, Arte, etc...) iframe'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: h5p
name: 'freier Embed'
sortOrder: 4
