field: a6ca8dd3-3275-44ec-9e6c-68cf3996ce56
fieldLayouts:
  ac958b74-6b9a-4aad-8dd7-1dd43779e4b7:
    tabs:
      -
        elements:
          -
            fieldUid: 5664480a-dfb1-4efd-a9db-aeca4b02ee0d
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 6079e3ae-30bb-4418-91ac-69c87e69a243
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 4a6756ad-3519-497a-baaf-e361088130e3
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  4a6756ad-3519-497a-baaf-e361088130e3:
    contentColumnType: text
    fieldGroup: null
    handle: urheber_nested
    instructions: ''
    name: urheber
    searchable: false
    settings:
      availableTransforms: ''
      availableVolumes: ''
      cleanupHtml: true
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: ''
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: ''
      showHtmlButtonForNonAdmins: ''
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  5664480a-dfb1-4efd-a9db-aeca4b02ee0d:
    contentColumnType: text
    fieldGroup: null
    handle: h5p_slider
    instructions: "hier bitte den vollständigen embed Code angeben. Beispiel:\r\n<iframe src=\"https://h5p.test-dilewe.de/wp-admin/admin-ajax.php?action=h5p_embed&id=19\" width=\"958\" height=\"918\" frameborder=\"0\" allowfullscreen=\"allowfullscreen\"></iframe><script src=\"https://h5p.test-dilewe.de/wp-content/plugins/h5p/h5p-php-library/js/h5p-resizer.js\" charset=\"UTF-8\"></script>"
    name: 'Freier Embed (H5P, Arte, etc...) iframe'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  6079e3ae-30bb-4418-91ac-69c87e69a243:
    contentColumnType: text
    fieldGroup: null
    handle: unterschrift_nested
    instructions: ''
    name: __blank__
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: h5p
name: 'iframe einbetten (z.B. H5P, Geogebra, etc. )'
sortOrder: 10
