field: 4af3b294-4ebe-4043-9f2c-63468570f33f
fieldLayouts:
  2f0ebf91-35c0-4e3c-9891-9b0473ddd70f:
    tabs:
      -
        elements:
          -
            fieldUid: feca27ea-2b34-409c-978d-19e6713b68de
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  feca27ea-2b34-409c-978d-19e6713b68de:
    contentColumnType: string
    fieldGroup: null
    handle: bild
    instructions: 'Das Heroimage ist ein Bild auf voller breite'
    name: Bild
    searchable: true
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds:
        - image
        - video
      defaultUploadLocationSource: 'volume:5f0e5dbb-8cba-49d5-8a1c-e7b7bf94b7a5'
      defaultUploadLocationSubpath: ''
      limit: '1'
      localizeRelations: false
      previewMode: full
      restrictFiles: '1'
      selectionLabel: ''
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: true
      singleUploadLocationSource: 'volume:5f0e5dbb-8cba-49d5-8a1c-e7b7bf94b7a5'
      singleUploadLocationSubpath: bilder
      source: null
      sources: '*'
      targetSiteId: null
      useSingleFolder: true
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
handle: heroimage
name: Heroimage
sortOrder: 8
