field: 4af3b294-4ebe-4043-9f2c-63468570f33f
fieldLayouts:
  3f414451-dea2-4e97-a0e0-f6cf0e82cb25:
    tabs:
      -
        elements:
          -
            fieldUid: be6c7977-6abe-4d50-867e-c83fba2dcc42
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 598c5967-7952-405c-a9ba-84cc4ead670d
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 6e09b14e-c248-4823-8ff7-e19220e3b632
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: ace20deb-a983-4dc3-9573-30b326cb325e
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  598c5967-7952-405c-a9ba-84cc4ead670d:
    contentColumnType: string
    fieldGroup: null
    handle: tabs
    instructions: ''
    name: __blank__
    searchable: false
    settings:
      columns:
        __assoc__:
          -
            - d4db5f58-a7eb-40fc-9b9a-b68640320bd4
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - 35aaa38f-a3ed-435f-8616-1d9cbc7fc65c
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - 2a00f674-40ee-4839-8c96-58a2a4b3858e
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - 7b42d4fa-55e9-4655-89d5-bf1eccd4cf8f
            -
              __assoc__:
                -
                  - width
                  - ''
      contentTable: '{{%stc_37_tabs}}'
      fieldLayout: matrix
      maxRows: '99'
      minRows: '1'
      placeholderKey: null
      propagationMethod: all
      selectionLabel: 'Tab hinzufügen'
      staticField: ''
    translationKeyFormat: null
    translationMethod: site
    type: verbb\supertable\fields\SuperTableField
  6e09b14e-c248-4823-8ff7-e19220e3b632:
    contentColumnType: boolean
    fieldGroup: null
    handle: nummerierung
    instructions: ''
    name: Nummerierung
    searchable: false
    settings:
      default: true
      offLabel: Inaktiv
      onLabel: Aktiv
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
  ace20deb-a983-4dc3-9573-30b326cb325e:
    contentColumnType: string
    fieldGroup: null
    handle: hilfsvideo_qs
    instructions: ''
    name: Hilfsvideo
    searchable: false
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds:
        - video
      defaultUploadLocationSource: 'volume:5f0e5dbb-8cba-49d5-8a1c-e7b7bf94b7a5'
      defaultUploadLocationSubpath: ''
      limit: '1'
      localizeRelations: false
      previewMode: full
      restrictFiles: '1'
      selectionLabel: ''
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:5f0e5dbb-8cba-49d5-8a1c-e7b7bf94b7a5'
      singleUploadLocationSubpath: help_videos
      source: null
      sources: '*'
      targetSiteId: null
      useSingleFolder: true
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  be6c7977-6abe-4d50-867e-c83fba2dcc42:
    contentColumnType: string
    fieldGroup: null
    handle: kastentyp
    instructions: ''
    name: Kastentyp
    searchable: false
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - 'Tab-Kasten Inhalt'
            -
              - value
              - tabkasten
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - 'Tab-Kasten Aufgaben'
            -
              - value
              - aufgabenkasten
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Förderfenster
            -
              - value
              - foerderfenster
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Stern-Differenzierung
            -
              - value
              - stern_differenzierung
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
handle: querslider
name: Tab-Kasten
sortOrder: 13
