field: a6ca8dd3-3275-44ec-9e6c-68cf3996ce56
fieldLayouts:
  7b973b72-81a4-400b-a6c8-f778d79326c4:
    tabs:
      -
        elements:
          -
            fieldUid: 6161e74c-4d09-4727-a705-b9f7d0c17542
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 7609f33a-6a81-4b7d-9d5b-b0c0a3ba4bd3
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 597eefdb-3e9a-43d6-b247-cba5ca05b3e4
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  597eefdb-3e9a-43d6-b247-cba5ca05b3e4:
    contentColumnType: text
    fieldGroup: null
    handle: tabelle
    instructions: 'Hier kann eine eigene Tabelle angelegt werden'
    name: tabelle
    searchable: false
    settings:
      columnsAddRowLabel: 'Spalte hinzufügen'
      columnsInstructions: 'Hier können die Spalten der Tabelle definiert werden'
      columnsLabel: Spalte
      rowsAddRowLabel: 'Zeile hinzufügen'
      rowsInstructions: 'Hier können Zeilen zur Tabelle hinzugefügt werden'
      rowsLabel: Zeile
    translationKeyFormat: null
    translationMethod: none
    type: supercool\tablemaker\fields\TableMakerField
  6161e74c-4d09-4727-a705-b9f7d0c17542:
    contentColumnType: string
    fieldGroup: null
    handle: art
    instructions: ''
    name: Art
    searchable: false
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - 'einfache Tabelle'
            -
              - value
              - simple-table
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - 'mit Kopfzeile'
            -
              - value
              - table-headrow
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'mit Kopfspalte'
            -
              - value
              - table-headcolumn
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Kopfzeile und Kopfspalte'
            -
              - value
              - table-both
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  7609f33a-6a81-4b7d-9d5b-b0c0a3ba4bd3:
    contentColumnType: boolean
    fieldGroup: null
    handle: minwidth
    instructions: ''
    name: Mindesbreite
    searchable: false
    settings:
      default: false
      offLabel: null
      onLabel: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
handle: tabellen
name: Tabellen
sortOrder: 6
