field: 4af3b294-4ebe-4043-9f2c-63468570f33f
fieldLayouts:
  3a868e6b-d39a-47ff-a26f-0617a1de4ff7:
    tabs:
      -
        elements:
          -
            fieldUid: 398e22d2-53b7-4b5d-ad3b-a49be0f8d8cb
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 54232222-a441-4047-9123-3d1ecdbbb84c
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  398e22d2-53b7-4b5d-ad3b-a49be0f8d8cb:
    contentColumnType: text
    fieldGroup: null
    handle: test
    instructions: ''
    name: test
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  54232222-a441-4047-9123-3d1ecdbbb84c:
    contentColumnType: text
    fieldGroup: null
    handle: test2
    instructions: ''
    name: test2
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: test
name: test
sortOrder: 15
