field: a6ca8dd3-3275-44ec-9e6c-68cf3996ce56
fieldLayouts:
  0423c727-9f79-4a77-bc9f-c70c4f420998:
    tabs:
      -
        elements:
          -
            fieldUid: c1b00867-6fb3-442f-8c0d-68a94c67dde0
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 14c772fd-fc27-4662-b099-da4a6a450198
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 73237106-4fe2-4e8a-9884-6881a0fa7a3b
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: f30495f8-fa20-4069-94be-c63e1c19fc25
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            fieldUid: 93ae788b-e74c-4e44-9667-c3d8c943158f
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            fieldUid: 4e77c30a-1d3f-4b58-9d28-9615eb69312b
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            fieldUid: 9f17e5a4-5f3a-4868-83a8-755be2b21edb
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  14c772fd-fc27-4662-b099-da4a6a450198:
    contentColumnType: string
    fieldGroup: null
    handle: bilder
    instructions: ''
    name: Bilder
    searchable: false
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds:
        - image
      defaultUploadLocationSource: 'volume:5f0e5dbb-8cba-49d5-8a1c-e7b7bf94b7a5'
      defaultUploadLocationSubpath: ''
      limit: '1'
      localizeRelations: false
      previewMode: full
      restrictFiles: '1'
      selectionLabel: ''
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: true
      singleUploadLocationSource: 'volume:5f0e5dbb-8cba-49d5-8a1c-e7b7bf94b7a5'
      singleUploadLocationSubpath: bilder/
      source: null
      sources: '*'
      targetSiteId: null
      useSingleFolder: true
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  4e77c30a-1d3f-4b58-9d28-9615eb69312b:
    contentColumnType: boolean
    fieldGroup: null
    handle: hideButtons
    instructions: ''
    name: 'Buttons ausblenden'
    searchable: false
    settings:
      default: false
      offLabel: null
      onLabel: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
  73237106-4fe2-4e8a-9884-6881a0fa7a3b:
    contentColumnType: text
    fieldGroup: null
    handle: bildunterschrift
    instructions: ''
    name: Bildunterschrift
    searchable: false
    settings:
      availableTransforms: ''
      availableVolumes: ''
      cleanupHtml: true
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: erweitert.json
      removeEmptyTags: '1'
      removeInlineStyles: ''
      removeNbsp: ''
      showHtmlButtonForNonAdmins: '1'
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  93ae788b-e74c-4e44-9667-c3d8c943158f:
    contentColumnType: string
    fieldGroup: null
    handle: bildposition
    instructions: ''
    name: Bildposition
    searchable: false
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - 'Links im Text'
            -
              - value
              - linksImText
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Rechts im Text'
            -
              - value
              - rechtsImText
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Über dem Text'
            -
              - value
              - ueberDemText
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  9f17e5a4-5f3a-4868-83a8-755be2b21edb:
    contentColumnType: string(255)
    fieldGroup: null
    handle: infoLink
    instructions: ''
    name: Infolink
    searchable: false
    settings:
      maxLength: '255'
      placeholder: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Url
  c1b00867-6fb3-442f-8c0d-68a94c67dde0:
    contentColumnType: mediumtext
    fieldGroup: null
    handle: text
    instructions: ''
    name: Text
    searchable: true
    settings:
      availableTransforms: ''
      availableVolumes: ''
      cleanupHtml: true
      columnType: mediumtext
      configSelectionMode: choose
      defaultTransform: de88bd6b-3cd6-4856-8aee-ebd53ec23905
      manualConfig: ''
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: erweitert.json
      removeEmptyTags: '1'
      removeInlineStyles: ''
      removeNbsp: ''
      showHtmlButtonForNonAdmins: '1'
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  f30495f8-fa20-4069-94be-c63e1c19fc25:
    contentColumnType: string
    fieldGroup: null
    handle: bildbreite
    instructions: ''
    name: Bildbreite
    searchable: false
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - 38.2%
            -
              - value
              - '38.2'
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - 61.8%
            -
              - value
              - '61.8'
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 100%
            -
              - value
              - '100'
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
handle: textMitOhneBild
name: 'Text mit Bild'
sortOrder: 2
