field: a6ca8dd3-3275-44ec-9e6c-68cf3996ce56
fieldLayouts:
  8617874a-72e6-4d3d-b51f-59d19c30903e:
    tabs:
      -
        elements:
          -
            fieldUid: 7f0ad484-fedd-4d6e-957f-5dbd695c6197
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 30dd3cb8-a20a-467e-8276-1e01a0046518
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 4c872a9c-890c-4e3b-9ba7-2eabc8c108a9
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  30dd3cb8-a20a-467e-8276-1e01a0046518:
    contentColumnType: string
    fieldGroup: null
    handle: groesse
    instructions: ''
    name: Größe
    searchable: false
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - H2
            -
              - value
              - h2
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - H3
            -
              - value
              - h3
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - H4
            -
              - value
              - h4
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - H5
            -
              - value
              - h5
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - H6
            -
              - value
              - h6
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  4c872a9c-890c-4e3b-9ba7-2eabc8c108a9:
    contentColumnType: string(255)
    fieldGroup: null
    handle: infoLink
    instructions: ''
    name: InfoLink
    searchable: false
    settings:
      maxLength: '255'
      placeholder: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Url
  7f0ad484-fedd-4d6e-957f-5dbd695c6197:
    contentColumnType: text
    fieldGroup: null
    handle: ueberschrift
    instructions: ''
    name: Überschrift
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: ueberschrift
name: Überschrift
sortOrder: 1
