field: 35aaa38f-a3ed-435f-8616-1d9cbc7fc65c
fieldLayouts:
  995ddb36-0f0d-432b-b236-8c3d2b101eab:
    tabs:
      -
        elements:
          -
            fieldUid: eba51c22-6181-4f80-a38a-43757c3ceb53
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: a5ad4e4f-ae6c-489f-b9d5-a1bd5b33e0ab
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 237e46db-e5bb-4332-bd23-34ca9ee5c43a
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  237e46db-e5bb-4332-bd23-34ca9ee5c43a:
    contentColumnType: string(255)
    fieldGroup: null
    handle: infoLink
    instructions: ''
    name: Infolink
    searchable: false
    settings:
      maxLength: '255'
      placeholder: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Url
  a5ad4e4f-ae6c-489f-b9d5-a1bd5b33e0ab:
    contentColumnType: string
    fieldGroup: null
    handle: groesse
    instructions: ''
    name: __blank__
    searchable: false
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - h2
            -
              - value
              - h2
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - h3
            -
              - value
              - h3
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - h4
            -
              - value
              - h4
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - h5
            -
              - value
              - h5
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - h6
            -
              - value
              - h6
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  eba51c22-6181-4f80-a38a-43757c3ceb53:
    contentColumnType: text
    fieldGroup: null
    handle: ueberschrift
    instructions: ''
    name: __blank__
    searchable: false
    settings:
      availableTransforms: ''
      availableVolumes: ''
      cleanupHtml: true
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: erweitert.json
      removeEmptyTags: '1'
      removeInlineStyles: ''
      removeNbsp: ''
      showHtmlButtonForNonAdmins: '1'
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
handle: ueberschrift
name: Überschrift
sortOrder: 1
