field: ab6348a4-5bdf-49af-91a3-b0782152a42c
fieldLayouts:
  0c5dc9b7-b8b9-4d31-be45-ce2ed308123c:
    tabs:
      -
        elements:
          -
            fieldUid: 1607027e-5ef9-41ae-ab7b-ebba00b69bfb
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 5bd9741b-d190-46e6-a06e-c0b99e2537a6
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 56f54c78-e4d7-4560-b357-1ccb9729f01e
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: c929e968-ab1d-46f5-8446-1467d81e9ad0
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  1607027e-5ef9-41ae-ab7b-ebba00b69bfb:
    contentColumnType: string
    fieldGroup: null
    handle: videoformat
    instructions: ''
    name: Videoformat
    searchable: false
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - querformat
            -
              - value
              - landscape
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - hochformat
            -
              - value
              - portrait
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  56f54c78-e4d7-4560-b357-1ccb9729f01e:
    contentColumnType: string
    fieldGroup: null
    handle: posterbild
    instructions: ''
    name: Posterbild
    searchable: false
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds:
        - image
      defaultUploadLocationSource: 'volume:5f0e5dbb-8cba-49d5-8a1c-e7b7bf94b7a5'
      defaultUploadLocationSubpath: ''
      limit: '1'
      localizeRelations: false
      previewMode: full
      restrictFiles: '1'
      selectionLabel: ''
      showSiteMenu: true
      showUnpermittedFiles: true
      showUnpermittedVolumes: true
      singleUploadLocationSource: 'volume:5f0e5dbb-8cba-49d5-8a1c-e7b7bf94b7a5'
      singleUploadLocationSubpath: bilder
      source: null
      sources: '*'
      targetSiteId: null
      useSingleFolder: true
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  5bd9741b-d190-46e6-a06e-c0b99e2537a6:
    contentColumnType: string
    fieldGroup: null
    handle: datei
    instructions: ''
    name: Video
    searchable: false
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds:
        - video
      defaultUploadLocationSource: 'volume:5f0e5dbb-8cba-49d5-8a1c-e7b7bf94b7a5'
      defaultUploadLocationSubpath: ''
      limit: '1'
      localizeRelations: false
      previewMode: full
      restrictFiles: '1'
      selectionLabel: ''
      showSiteMenu: true
      showUnpermittedFiles: true
      showUnpermittedVolumes: true
      singleUploadLocationSource: 'volume:5f0e5dbb-8cba-49d5-8a1c-e7b7bf94b7a5'
      singleUploadLocationSubpath: videos
      source: null
      sources: '*'
      targetSiteId: null
      useSingleFolder: true
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  c929e968-ab1d-46f5-8446-1467d81e9ad0:
    contentColumnType: text
    fieldGroup: null
    handle: videounterschrift
    instructions: ''
    name: Videounterschrift
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: videoDatei
name: Video
sortOrder: 2
