contentColumnType: string
fieldGroup: 802146cd-8552-4db9-b8ec-3e060400e229
handle: herovideo
instructions: 'Hier kann ein Video hochgeladen werden'
name: Herovideo
searchable: true
settings:
  allowSelfRelations: false
  allowUploads: true
  allowedKinds:
    - video
  defaultUploadLocationSource: 'volume:5f0e5dbb-8cba-49d5-8a1c-e7b7bf94b7a5'
  defaultUploadLocationSubpath: ''
  limit: '1'
  localizeRelations: false
  previewMode: full
  restrictFiles: '1'
  selectionLabel: ''
  showSiteMenu: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: true
  singleUploadLocationSource: 'volume:5f0e5dbb-8cba-49d5-8a1c-e7b7bf94b7a5'
  singleUploadLocationSubpath: videos
  source: null
  sources: '*'
  targetSiteId: null
  useSingleFolder: true
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
