contentColumnType: string
fieldGroup: 9e8f7a71-e303-41fe-951f-0809543d5404
handle: lizenzart
instructions: ''
name: Lizenzart
searchable: true
settings:
  optgroups: true
  options:
    -
      __assoc__:
        -
          - label
          - 'GNU Free Documentation License'
        -
          - value
          - GFDL
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'Creative Commons license (CC 4.0)'
        -
          - value
          - cc4
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - 'Creative Commons license (CC 3.0)'
        -
          - value
          - cc3
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'Creative Commons license (CC 2.0)'
        -
          - value
          - cc2
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'Creative Commons Zero (0)'
        -
          - value
          - cc0
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'Public Domain (C)'
        -
          - value
          - PD
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'all rights reserved ©'
        -
          - value
          - arrc
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
