contentColumnType: text
fieldGroup: 9e8f7a71-e303-41fe-951f-0809543d5404
handle: quelle
instructions: ''
name: Quelle
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '2'
  multiline: '1'
  placeholder: ''
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
