contentColumnType: text
fieldGroup: 3be8de49-f91f-4c91-a2e6-74f8ec7e8320
handle: stimmfeld_table
instructions: ''
name: Stimmfeld_table
searchable: false
settings:
  addRowLabel: 'Zeile hinzufügen'
  columnType: text
  columns:
    __assoc__:
      -
        - col1
        -
          __assoc__:
            -
              - handle
              - field0
            -
              - heading
              - Antwort1
            -
              - type
              - checkbox
            -
              - width
              - ''
      -
        - col10
        -
          __assoc__:
            -
              - handle
              - field9
            -
              - heading
              - '10'
            -
              - type
              - checkbox
            -
              - width
              - ''
      -
        - col11
        -
          __assoc__:
            -
              - handle
              - field10
            -
              - heading
              - '11'
            -
              - type
              - checkbox
            -
              - width
              - ''
      -
        - col12
        -
          __assoc__:
            -
              - handle
              - field11
            -
              - heading
              - '12'
            -
              - type
              - checkbox
            -
              - width
              - ''
      -
        - col13
        -
          __assoc__:
            -
              - handle
              - field12
            -
              - heading
              - 'Frage beantwortet ?'
            -
              - type
              - checkbox
            -
              - width
              - ''
      -
        - col2
        -
          __assoc__:
            -
              - handle
              - field1
            -
              - heading
              - '2'
            -
              - type
              - checkbox
            -
              - width
              - ''
      -
        - col3
        -
          __assoc__:
            -
              - handle
              - field2
            -
              - heading
              - '3'
            -
              - type
              - checkbox
            -
              - width
              - ''
      -
        - col4
        -
          __assoc__:
            -
              - handle
              - field3
            -
              - heading
              - '4'
            -
              - type
              - checkbox
            -
              - width
              - ''
      -
        - col5
        -
          __assoc__:
            -
              - handle
              - field4
            -
              - heading
              - '5'
            -
              - type
              - checkbox
            -
              - width
              - ''
      -
        - col6
        -
          __assoc__:
            -
              - handle
              - field5
            -
              - heading
              - '6'
            -
              - type
              - checkbox
            -
              - width
              - ''
      -
        - col7
        -
          __assoc__:
            -
              - handle
              - field6
            -
              - heading
              - '7'
            -
              - type
              - checkbox
            -
              - width
              - ''
      -
        - col8
        -
          __assoc__:
            -
              - handle
              - field7
            -
              - heading
              - '8'
            -
              - type
              - checkbox
            -
              - width
              - ''
      -
        - col9
        -
          __assoc__:
            -
              - handle
              - field8
            -
              - heading
              - '9'
            -
              - type
              - checkbox
            -
              - width
              - ''
  defaults:
    -
      __assoc__:
        -
          - col1
          - ''
        -
          - col10
          - ''
        -
          - col11
          - ''
        -
          - col12
          - ''
        -
          - col13
          - ''
        -
          - col2
          - ''
        -
          - col3
          - ''
        -
          - col4
          - ''
        -
          - col5
          - ''
        -
          - col6
          - ''
        -
          - col7
          - ''
        -
          - col8
          - ''
        -
          - col9
          - ''
  maxRows: ''
  minRows: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Table
