contentColumnType: text
fieldGroup: 9f04a027-e99f-4039-ba6f-8c3cf8e63728
handle: titelDerPublikation
instructions: ''
name: 'Titel der Publikation'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: text
  initialRows: 4
  multiline: ''
  placeholder: ''
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
