contentColumnType: string
fieldGroup: 802146cd-8552-4db9-b8ec-3e060400e229
handle: untertitel
instructions: ''
name: Untertitel
searchable: false
settings:
  contentTable: '{{%stc_untertitel}}'
  fieldLayout: table
  maxRows: ''
  minRows: ''
  placeholderKey: null
  propagationMethod: all
  selectionLabel: ''
  staticField: ''
translationKeyFormat: null
translationMethod: site
type: verbb\supertable\fields\SuperTableField
