# docker-compose.yml
# https://github.com/urbantrout/craftcms
version: '3.8'

services:
  nginx:
    image: nginx:alpine
    ports:
      - 80:80
    depends_on:
      - craft
    volumes_from:
      - craft
    volumes:
      - ./.docker/default.conf:/etc/nginx/conf.d/default.conf # nginx configuration (see below)
      # - ./assets:/var/www/html/web/assets # For static assets (media, js and css).

  craft:
    image: urbantrout/craftcms:mysql # Use mysql instead of postgresql
    depends_on:
      - mariadb
    # volumes:
      # - ./assets:/var/www/html/web/assets:z
      # - ./.docker/sql/:/var/www/html/storage/backups # Used for db restore on start.
      # - ./templates:/var/www/html/templates # Craft CMS template files
      # - ./translations:/var/www/html/translations
      # - ./redactor:/var/www/html/config/redactor
    environment:
      DEPENDENCIES: >- # additional composer packages
        yiisoft/yii2-redis
        craftcms/redactor:2.0.1
      CRAFTCMS_EMAIL: admin@company.com
      CRAFTCMS_USERNAME: admin
      CRAFTCMS_PASSWORD: adminadmin
      CRAFTCMS_SITENAME: Craft CMS Installation
      CRAFTCMS_SITEURL: http://dev.project.com # Optional

      AUTO_UPDATE: 'false' # Enable/disable auto updates for all composer packages (including Craft CMS, Default: true)

      REDIS_HOST: redis
      SESSION_DRIVER: redis
      CACHE_DRIVER: redis

      DB_DSN: mysql:host=mariadb;dbname=craft
      DB_SERVER: mariadb
      DB_NAME: craft
      DB_USER: craft
      DB_PASSWORD: secret
      DB_DATABASE: craft
      DB_SCHEMA: public
      DB_DRIVER: mysql
      DB_PORT: 3306
      DB_TABLE_PREFIX: ""
    healthcheck:
      test: "curl --fail nginx/admin || exit 1"
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 10s

  mariadb:
    image: mariadb:10.1
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: craft
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: craft
    ports:
      - 3306:3306
    volumes:
      # Persistent data
      - dbdata:/var/lib/mysql
      # - ./.docker/min_seed.sql:/docker-entrypoint-initdb.d/init.sql

  field-seeder:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
    entrypoint: ["bash", "-c", "mysql -h mariadb -u root -proot -e \"use craft; show tables;\""]
    depends_on:
      craft:
        condition: service_healthy
    

  redis:
    image: redis:4-alpine
    volumes:
      - redisdata:/data

volumes:
  dbdata:
  redisdata: