field: 598c5967-7952-405c-a9ba-84cc4ead670d
fieldLayouts:
  4c5349a8-dce7-4e96-8d8e-2781074e81ee:
    tabs:
      -
        elements:
          -
            fieldUid: d4db5f58-a7eb-40fc-9b9a-b68640320bd4
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 35aaa38f-a3ed-435f-8616-1d9cbc7fc65c
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 2a00f674-40ee-4839-8c96-58a2a4b3858e
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: ff073ac7-3d2c-434c-aaf1-d83dd75b4a8f
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  2a00f674-40ee-4839-8c96-58a2a4b3858e:
    contentColumnType: text
    fieldGroup: null
    handle: quellenangaben_q
    instructions: ''
    name: Quellenangaben
    searchable: true
    settings:
      availableTransforms: ''
      availableVolumes: ''
      cleanupHtml: true
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: erweitert.json
      removeEmptyTags: '1'
      removeInlineStyles: ''
      removeNbsp: ''
      showHtmlButtonForNonAdmins: '1'
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  35aaa38f-a3ed-435f-8616-1d9cbc7fc65c:
    contentColumnType: string
    fieldGroup: null
    handle: quersliderInhalt
    instructions: ''
    name: Inhalt
    searchable: true
    settings:
      contentTable: '{{%matrixcontent_quersliderinhalt}}'
      maxBlocks: '2'
      minBlocks: ''
      propagationMethod: all
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Matrix
  d4db5f58-a7eb-40fc-9b9a-b68640320bd4:
    contentColumnType: text
    fieldGroup: null
    handle: bezeichnung
    instructions: ''
    name: Tab-Bezeichnung
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  ff073ac7-3d2c-434c-aaf1-d83dd75b4a8f:
    contentColumnType: string
    fieldGroup: null
    handle: tabMedia
    instructions: ''
    name: 'Tab Medium'
    searchable: false
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds:
        - audio
        - video
      defaultUploadLocationSource: 'volume:5f0e5dbb-8cba-49d5-8a1c-e7b7bf94b7a5'
      defaultUploadLocationSubpath: ''
      limit: '1'
      localizeRelations: false
      previewMode: full
      restrictFiles: '1'
      selectionLabel: ''
      showSiteMenu: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:5f0e5dbb-8cba-49d5-8a1c-e7b7bf94b7a5'
      singleUploadLocationSubpath: audio
      source: null
      sources: '*'
      targetSiteId: null
      useSingleFolder: true
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
