field: 04719e38-9772-4c1e-8bbc-2552ec47c8b0
fieldLayouts:
  16ce302c-a4ce-4c1e-8293-123ff8ba6494:
    tabs:
      -
        elements:
          -
            fieldUid: ab6348a4-5bdf-49af-91a3-b0782152a42c
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  ab6348a4-5bdf-49af-91a3-b0782152a42c:
    contentColumnType: string
    fieldGroup: null
    handle: quersliderAufgabenElemente
    instructions: ''
    name: elemente
    searchable: true
    settings:
      contentTable: '{{%matrixcontent_querslideraufgabenelemente}}'
      maxBlocks: ''
      minBlocks: ''
      propagationMethod: all
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Matrix
