field: 7a536258-08a3-49a9-9301-f39ae9388993
fieldLayouts:
  ecf4fcc3-e882-4128-a866-e46213d314f0:
    tabs:
      -
        elements:
          -
            fieldUid: a7f1b10a-d584-432b-9157-9aeb8f3f06b7
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 9e4f6289-9ba3-4702-b421-b7bbf103bc92
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 2ead38ca-20cf-4fce-8d5c-381a1d7d2416
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  2ead38ca-20cf-4fce-8d5c-381a1d7d2416:
    contentColumnType: string
    fieldGroup: null
    handle: src
    instructions: ''
    name: 'vtt Datei'
    searchable: false
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds: null
      defaultUploadLocationSource: 'volume:5f0e5dbb-8cba-49d5-8a1c-e7b7bf94b7a5'
      defaultUploadLocationSubpath: ''
      limit: '1'
      localizeRelations: false
      previewMode: full
      restrictFiles: ''
      selectionLabel: ''
      showSiteMenu: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:5f0e5dbb-8cba-49d5-8a1c-e7b7bf94b7a5'
      singleUploadLocationSubpath: untertitel
      source: null
      sources: '*'
      targetSiteId: null
      useSingleFolder: true
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  9e4f6289-9ba3-4702-b421-b7bbf103bc92:
    contentColumnType: text
    fieldGroup: null
    handle: srclang
    instructions: 'de oder en ...'
    name: Sprache
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  a7f1b10a-d584-432b-9157-9aeb8f3f06b7:
    contentColumnType: string
    fieldGroup: null
    handle: closedcaption
    instructions: ''
    name: 'Closed Caption?'
    searchable: false
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - subtitles
            -
              - value
              - subtitles
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - captions
            -
              - value
              - captions
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
