#!/usr/bin/env bash
if [[ "$HOSTNAME" != "dev.dilewe.de" ]]; then
	echo "It's very likely that you don't want to execute this script, since it is meant for the dev.dilewe.de server."s
	exit
fi
cd /var/www/html/dilewe.de/systemx/

npm run build altenburg &
npm run build bettermarks &
npm run build juramuseum &
npm run build rdhessen &
npm run build lasub &
npm run build stifterverband &

wait
