#!/usr/bin/env bash
if [[ "$HOSTNAME" != "dev.dilewe.de" ]]; then
	echo "It's very likely that you don't want to execute this script, since it is meant for the dev.dilewe.de server."s
	exit
fi
cd /var/www/html/dilewe.de/systemx/

sudo -u www-data npm run build altenburg &
sudo -u www-data npm run build bettermarks &
sudo -u www-data npm run build juramuseum &
sudo -u www-data npm run build rdhessen &
sudo -u www-data npm run build lasub &
sudo -u www-data npm run build stifterverband &

wait
