#!/usr/bin/env bash
if [[ "$HOSTNAME" != "dev.dilewe.de" ]]; then
	echo "It's very likely that you don't want to execute this script, since it is meant for the dev.dilewe.de server."
	exit
fi
cd /var/www/html/dilewe.de/systemx/
git reset --hard
git pull
npm install
systemctl restart 'systemx@altenburg'
systemctl restart 'systemx@bettermarks'
systemctl restart 'systemx@juramuseum'
systemctl restart 'systemx@rdhessen'
systemctl restart 'systemx@lasub'
systemctl restart 'systemx@stifterverband'
