#!/usr/bin/env bash
if [[ "$HOSTNAME" != "dev.dilewe.de" ]]; then
	echo "It's very likely that you don't want to execute this script, since it is meant for the dev.dilewe.de server."
	exit
fi
cd /var/www/html/dilewe.de/systemx
# Make sure we're on the correct branch
git checkout master
# Don't just run `$ git pull`, as this might lead to conflicts
git fetch
git reset --hard origin/master
npm install
chown -R www-data:www-data /var/www/html/dilewe.de/systemx
systemctl restart 'systemx@altenburg'
systemctl restart 'systemx@bettermarks'
systemctl restart 'systemx@juramuseum'
systemctl restart 'systemx@rdhessen'
systemctl restart 'systemx@lasub'
systemctl restart 'systemx@stifterverband'
