enableVersioning: true
handle: autoren
name: Autoren
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primäre eintrag Seite'
      -
        - urlFormat
        - '{url}'
propagationMethod: all
siteSettings:
  53088da7-81a2-4f8f-990f-c8f14820cce7:
    enabledByDefault: true
    hasUrls: true
    template: autoren/_entry
    uriFormat: 'autoren/{slug}'
type: channel
