# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
name: Node.js CI

on:
  push:

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Linting
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 7.0.0-rc.2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          cache: 'pnpm'
      - run: pnpm i
      - run: pnpm lint
  notify:
    name: Notifications for this pipeline
    runs-on: ubuntu-latest
    if: ${{ failure() }}
    needs: [lint]
    steps:
      - name: Post Pipeline Fails to a Slack channel
        id: slack
        uses: slackapi/slack-github-action@v1.18.0
        with: # Slack channel id, channel name, or user id to post message.
          # See also: https://api.slack.com/methods/chat.postMessage#channels
          channel-id: '${{ secrets.SLACKCHANNEL_PROD }}'
          # For posting a simple plain text message
          slack-message: |
            GitHub Workflow error :warning:
            integration: ${{ needs.integration.result }}
            lint: ${{ needs.lint.result }}
            test: ${{ needs.test.result }}
            on commit : ${{ github.event.pull_request.html_url || github.event.head_commit.url }}
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACKTOKEN_SYSTEMX }}
